# Generated by Django 3.2.6 on 2021-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
